config/routes.rb
Rails.application.routes.draw do
  #je crée mes routes (mes liens urls), to: j'apelle mes méthodes (donc mes pages view.)
  get '/', to: 'homes#index', as: 'homes'
  get 'welcomes/:first_name', to: 'welcomes#user'

  #je crée mes routes dynamique pour mes models gossips
  resources :gossips #cette commande me permet de créer les 7 relations avec le REST vu dans le cour de mardi


  #je crée mes routes dynamique pour mes auteurs
  resources :auteurs

  #je crée mes routes dynamique pour mes cities
  resources :cities
  
  #mes routes page contacts
  get 'contacts', to: 'contacts#contactus'
  get 'contacts/christophe', to: 'contacts#contact_christophe'
  get 'contacts/lucas', to: 'contacts#contact_lucas'

  #mes routes page team
  get 'teams', to: 'teams#home'
  get 'teams/christophe', to: 'teams#christophe'
  get 'teams/lucas', to: 'teams#lucas'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	#je fais ma relation qu'une city peut avoir plusieur users
	has_many :users
end

app/models/create_private_message.rb
class CreatePrivateMessage < ApplicationRecord
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	#La relation est qu'un gossip est écrit pas un seul user
	belongs_to :user
	#mais qu'un gossip peut avoir plusieur tag
	has_many :tag_gossips
	has_many :tags, through: :tag_gossip

 #je met mes validations
 validates :title,
 presence: true,
 length: { minimum: 3, maximum: 14 }

 validates :content,
 presence: true

end

app/models/message_prive.rb
class MessagePrive < ApplicationRecord
	#je permet une relation sender et recipient avec la class user
	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	#cette relation: un tag peut avoir plusieur gossip
	has_many :tagGossips
	has_many :Gossips, through: :tagGossip
end

app/models/tag_gossip.rb
class TagGossip < ApplicationRecord
	#cette relation intermédiaire me permet de faire le lien entre gossip et tag
	belongs_to :gossip
	belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
	#j'effectue ma relation: 1 utilisateur appartient à 1 ville
	belongs_to :city
	#l'utilisateur peut avoir écrit plusieur gossips
	has_many :gossips
	#qu'un user peut envoyer plusieur message et recevoir plusieur message
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "MessagePrive"
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "MessagePrive"
end

app/controllers/auteurs_controller.rb
class AuteursController < ApplicationController
  def index
    # Méthode qui récupère tous les auteurs et les envoie à la view index (index.html.erb) pour affichage
    @users = User.all
    @cities = City.all
  end

  def show
    # Méthode qui récupère l'auteur concerné et l'envoie à la view show (show.html.erb) pour affichage
    @user = User.find(params[:id])
    @cities = City.all
 end

  def new
    # Méthode qui crée un auteur vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
    @users = User.all
  end

  def create
    # Méthode qui créé un auteur à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher l'auteur' créé)
    @user = User.all
  end

  def edit
    # Méthode qui récupère l'auteur concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
    @user = User.all
  end

  def update
    # Méthode qui met à jour l'auteur à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher l'auteur' modifié)
    @user = User.all
  end

  def destroy
    # Méthode qui récupère l'auteur' concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
    @user = User.all
  end
end

app/controllers/cities_controller.rb
  class CitiesController < ApplicationController
    def index

    end

    def show
      @gossips = Gossip.all
      @city = City.find(params[:id])
      @users = User.all

    end

    def new
      # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
    end

    def create

    end

    def edit
      # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
    end

    def update

    end

    def destroy
      # Méthode qui récupère le potin concerné et le détruit en base
      # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
    end
  end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
 def index
   # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
   @gossips = Gossip.all
   @users = User.all
 end

 def show
   # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
   @gossip = Gossip.find(params[:id])
   @users = User.all
   @cities = City.all
end

 def new
   # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
 end

 def create
   # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
   # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
   # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
   @gossip = Gossip.new(user_id: 2, title: params[:title], content: params[:content])

   if @gossip.save
     redirect_to gossips_path
   else
     render 'gossips/show'
   end
 end

 def edit
   # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
   @gossip = Gossip.find(params[:id])
 end

 def update
   @gossip = Gossip.find(params[:id])
   if @gossip.update(title: params[:title], content: params[:content])
     redirect_to gossips_path
   else
     render :edit
   end
 end

 def destroy
   @gossip = Gossip.find(params[:id])
  if @gossip.destroy
    redirect_to gossips_path
  else
    render :show
  end
 end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #je récupère mes tout mes gossip de mes models pour pouvoir les utiliser dans mes views
    @gossip = Gossip.all
    @user = User.all
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    #je récupère mes tout mes gossip de mes models pour pouvoir les utiliser dans mes views
    @gossip = Gossip.all
    @user = User.all
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  #je crée mes controllers et ma page home
  def home
  end

  def christophe
  end

  def lucas
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  #je crée mes controllers et ma page home
  def home
  end

  def christophe
  end

  def lucas
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auteur_helper.rb
module AuteurHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossip/content.html.erb
<h1>GOSSIP TIME! </h1>

<h2>Titre : <%= @gossip.find(params[:id]).title %> </h2>

<h3>Ecrit par:
  <% g = @gossip.find(params[:id]) %> <% h = g.user_id %>
  <!-- je créer mon liens vers la page de l'autre sur le nom et prénom -->
 <%= link_to "#{@user.find(h).first_name} #{@user.find(h).last_name}", auteurs_path(h) %>
</h3>

<p> le : <%=@gossip.find(params[:id]).created_at.strftime("%d/%m/%Y") %> <br/>
dernière modification: <%=@gossip.find(params[:id]).updated_at.strftime("%d/%m/%Y") %> </p>

<p> <%= @gossip.find(params[:id]).content %> </p>

app/views/gossips/create.html.erb
<h1>Gossips#create</h1>
<p>Find me in app/views/gossips/create.html.erb</p>

app/views/gossips/destroy.html.erb
<h1>Gossips#destroy</h1>
<p>Find me in app/views/gossips/destroy.html.erb</p>

app/views/gossips/edit.html.erb
    <!-- ... -->
<br><br><br>

<center>
    <%= form_tag url_for(action:'update'), method: "patch" do %>

      <%= label_tag 'Title' %><br>
      <%= text_field_tag 'title'  %>
      <br /> <br />

      <%= label_tag 'Content' %><br>
      <%= text_area_tag 'content' %>
      <br /> <br />

      <%= submit_tag "Edit Post" %>
    <% end %>

</center>

app/views/gossips/index.html.erb
<style>
  .jumbotron {
    height: 500px;
    background-image: url("https://d3v4jsc54141g1.cloudfront.net/uploads/project/avatar/141622/large_Capture_d_e_cran_2019-06-04_14.26.29-1559651857.png");
    background-repeat: no-repeat;
    background-size:cover;
    background-attachment:fixed;
  }
</style>


<div style="background-color:pink;" class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4" style="text-align:center; padding-top:80px; color:white;">Hello les MOUSS'</h1>
    <p style="text-align:center; padding-top:40px; padding-bottom:40px; color:white;" class="lead">Vous êtes à la recherche de tous les gossips de THP ? Pas besoin de chercher bien loin !</p>
  </div>
</div>

<p style="text-align:center;">Tu souhaites créer ton propre Gossip ?  </p>
<p style="text-align:center;">Rien de plus facile ! <%= link_to "Crée le!", new_gossip_path %>  </p>

<br><br>

<!-- je récupère mes author et titre de chaque gossips. -->
<% @gossips.each do |index| %>
<center>
<div class="card" style="width: 18rem; text-align:center;">
  <img class="card-img-top" src="https://is3-ssl.mzstatic.com/image/thumb/Podcasts113/v4/dc/27/a1/dc27a1eb-2307-fe47-342e-6fb84618f5a8/mza_8792713575073991728.jpg/600x600bb.jpg" alt="Card image cap">
  <div class="card-body">
    <p class="card-text"> <%= index.title %> </p>
    <p class="card-text"><%  a = index.user_id %> Gossipeur : <%= @users.find(a).first_name %></p>
    <a href="http://localhost:3000/gossips/<%=index.id%>" class="btn btn-primary"> SEE THIS GOSSIP! </a>
  </div>
</div>
<br>
</center>
<% end %>

app/views/gossips/new.html.erb
    <!-- ... -->
<br><br><br>

<center>
    <%= form_tag url_for(action:'create'), method: "post" do %>

      <%= label_tag 'Title' %><br>
      <%= text_field_tag 'title'  %>
      <br /> <br />

      <%= label_tag 'Content' %><br>
      <%= text_area_tag 'content' %>
      <br /> <br />

      <%= submit_tag "Create Post" %>
<!--  test alerts
      <div class="alert alert-success" role="alert">
        Le Gossip a été créé
      </div>
      <div class="alert alert-info" role="alert">
        Le Gossip n'a pas été créé
      </div>
-->
    <% end %>

</center>

app/views/gossips/show.html.erb
<h1>GOSSIP TIME! </h1>

<h2>Titre : <%= @gossip.title %> </h2>

<h3>Ecrit par:
  <!-- je créer mon liens vers la page de l'autre sur le nom et prénom -->
 <%= link_to "#{@users.find(@gossip.user_id).first_name} #{@users.find(@gossip.user_id).last_name}", auteur_path(@gossip.user_id) %>
</h3>

<p> le : <%=@gossip.created_at.strftime("%d/%m/%Y") %> <br/>
dernière modification: <%=@gossip.updated_at.strftime("%d/%m/%Y") %> <br/>
dans la ville : <%=link_to "#{@cities.find(@users.find(@gossip.user_id).city_id).name}", city_path(@users.find(@gossip.user_id).city_id) %>
</p>


<p> <%= @gossip.content %> </p>


<p> <a href="<%= edit_gossip_path(@gossip.id) %>" class="btn btn-primary"> Edit </a>
<a href="<%=gossip_path(@gossip.id)%>" class="btn btn-danger" data-confirm="Etes-vous sur de vouloir supprimer ce post?" data-method="DELETE">Supprimer</a> </p>

app/views/gossips/update.html.erb
<h1>Gossips#update</h1>
<p>Find me in app/views/gossips/update.html.erb</p>