config/routes.rb
Rails.application.routes.draw do
  #je crée mes routes (mes liens urls), to: j'apelle mes méthodes (donc mes pages view.)
  get '/', to: 'homes#index', as: 'homes'
  get 'welcomes/:first_name', to: 'welcomes#user'

  #je crée mes routes dynamique pour mes models gossips
  resources :gossips #cette commande me permet de créer les 7 relations avec le REST vu dans le cour de mardi


  #je crée mes routes dynamique pour mes auteurs
  resources :auteurs

  #je crée mes routes dynamique pour mes cities
  resources :cities
  
  #mes routes page contacts
  get 'contacts', to: 'contacts#contactus'
  get 'contacts/christophe', to: 'contacts#contact_christophe'
  get 'contacts/lucas', to: 'contacts#contact_lucas'

  #mes routes page team
  get 'teams', to: 'teams#home'
  get 'teams/christophe', to: 'teams#christophe'
  get 'teams/lucas', to: 'teams#lucas'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	#je fais ma relation qu'une city peut avoir plusieur users
	has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	#La relation est qu'un gossip est écrit pas un seul user
	belongs_to :user
	#mais qu'un gossip peut avoir plusieur tag
	has_many :tag_gossips
	has_many :tags, through: :tag_gossip

 #je met mes validations
 validates :title,
 presence: true,
 length: { minimum: 3, maximum: 14 }

 validates :content,
 presence: true

end

app/models/message_prive.rb
class MessagePrive < ApplicationRecord
	#je permet une relation sender et recipient avec la class user
	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	#cette relation: un tag peut avoir plusieur gossip
	has_many :tagGossips
	has_many :Gossips, through: :tagGossip
end

app/models/tag_gossip.rb
class TagGossip < ApplicationRecord
	#cette relation intermédiaire me permet de faire le lien entre gossip et tag
	belongs_to :gossip
	belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
	#j'effectue ma relation: 1 utilisateur appartient à 1 ville
	belongs_to :city
	#l'utilisateur peut avoir écrit plusieur gossips
	has_many :gossips
	#qu'un user peut envoyer plusieur message et recevoir plusieur message
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "MessagePrive"
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "MessagePrive"
end

app/controllers/cities_controller.rb
  class CitiesController < ApplicationController
    def index

    end

    def show
      @gossips = Gossip.all
      @city = City.find(params[:id])
      @users = User.all

    end

    def new
      # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
    end

    def create

    end

    def edit
      # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
    end

    def update

    end

    def destroy
      # Méthode qui récupère le potin concerné et le détruit en base
      # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #je récupère mes tout mes gossip de mes models pour pouvoir les utiliser dans mes views
    @gossip = Gossip.all
    @user = User.all
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    #je récupère mes tout mes gossip de mes models pour pouvoir les utiliser dans mes views
    @gossip = Gossip.all
    @user = User.all
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  #je crée mes controllers et ma page home
  def home
  end

  def christophe
  end

  def lucas
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  #je crée mes controllers et ma page home
  def home
  end

  def christophe
  end

  def lucas
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auteur_helper.rb
module AuteurHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProjet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Lien boostrap -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "HOME Montpellier", homes_path %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
<!-- style="padding-left:10px;" me permet de faire des espaces entre les boutons -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li style="padding-left:10px;"class="nav-item">
            <%= link_to "Gossips", gossips_path %>
          </li>
          <li style="padding-left:10px;"class="nav-item">
            <%= link_to "Team", teams_path %>
          </li>
          <li style="padding-left:10px;" class="nav-item">
            <%= link_to "Contact", contacts_path %>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>


    </nav>

    <%= yield %>

  </body>
</html>